<div class="container">
<center>
<h2>TEMPLATE REPORT FOR LOGISTIC REGRESSION</h2>

<h2>CASE: MARKET RESEARCH, MARKET SEGMENTATION, PURCHASE DRIVERS</h2>

</center>
<hr>

<!--The chunk above calls the code of logistic regression. It also  calls all needed libraries. The code of this chunk is silently executed but not showned in report-->

```{r echo=FALSE,include=FALSE,results='hide'}
library(xtable)
library(Hmisc)
source('../../code/logreg/logreg.R')
```
<center><h4>The Data</h4>
<hr>

```{r echo=FALSE,results='asis',warning=FALSE,error=FALSE,message=FALSE,resize.width=0.3}
data<-cbind(crs$nobs,length(crs$sample),length(crs$validate),length(crs$test))
data<-as.data.frame(data)
colnames(data)<-c("No.of Observations","No.of Sample","No.of Validation","No.of Train")
data<-xtable(data,caption="Dataset logistic regression")
print(data,type="html",html.table.attributes = "class='table table-striped table-hover table-bordered'",caption.placement="top")

```
</center>
<br>
<center><h4>The Model</h4>
<hr>

```{r echo=FALSE,results='asis',warning=FALSE,error=FALSE,message=FALSE,resize.width=0.3}
model<-xtable(summary(crs$glm),caption="Logistic Regression Model")
print(model,type="html",html.table.attributes = "class='table table-striped table-hover table-bordered'",caption.placement="top")

```
</center>
<br>
<center><h4>The Anova Table</h4>
<hr>

```{r echo=FALSE,results='asis',warning=FALSE,error=FALSE,message=FALSE,resize.width=0.3}
ano<-xtable(anova(crs$glm, test="Chisq"),caption="Anova Table")
print(ano,type="html",html.table.attributes = "class='table table-striped table-hover table-bordered'",caption.placement="top")

```
</center>
</br>
<center><h4>Generate the confusion matrix</h4>
<hr>

```{r echo=FALSE,results='asis',warning=FALSE,error=FALSE,message=FALSE,resize.width=0.3}
conf<-xtable(cm,caption="Confusion matrix")
print(conf,type="html",html.table.attributes = "class='table table-striped table-hover table-bordered'",caption.placement="top")

```
</center>
</br>
<center><h4>Generate percetanges for confusion matrix</h4>
<hr>

```{r echo=FALSE,results='asis',warning=FALSE,error=FALSE,message=FALSE,resize.width=0.3}
confp<-xtable(cmp,caption="Confusion matrix percentages")
print(confp,type="html",html.table.attributes = "class='table table-striped table-hover table-bordered'",caption.placement="top")

```
</center>
<br>
</div>